### ISSUE TITLE
I'd like to try your nvim config

### ISSUE THREAD

**Issue by jorgesca** [mathjiajia/config.nvim#3]
Hi, this isn't really an issue.  I just found your nvim config while looking for ways to configure neovim for latex writing. I tried running your config directly to see how it looked and worked, but I got some errors. Upon inspection, I find the init.lua is not loading any plugins nor options. I am missing something? What would I have to do to test your config? I'm on Linux, btw.
Thanks in advance,

**Comment by mathjiajia** [comment]
I didn’t set my config well for the first time use.
So you should try to:
1, comment the line 1 and line 31 of `init.lua`.
2, run nvim, and wait for 1 second;
3, use command `PackerSync`.
4, uncomment line 1 and line 31 of `init.lua`.

If there are some errors in step 2, just press `Enter` to ignore.
You need to wait 1 second because I delay the loading of packer plugins list.
See lines 42 - 45 of `plugin/options.lua`.

If there is some error related to `f3fora/nvim-texlabconfig`, please refer to its repo or remove this plugin.
It needs `go` to build the executable file.

Please revise the first 7 lines of `plugin/option.lua` for your system.
Please revise `lua/lsp/texlab` for your system as well (such as using 'zathura`).
